### ISSUE TITLE
Cant parse match 7837952900 (Riyadh Masters 2024)

### ISSUE THREAD

**Issue by kintawer** [yasp-dota/parser#71]
It looks like all Riyadh Masters 2024 matches are not working at all

Replay url: http://replay161.valve.net/570/7837952900_480867985.dem.bz2
OpenDota url: https://www.opendota.com/matches/7837952900

Java traceback:
```
replay-parser_1   | java.lang.ArrayIndexOutOfBoundsException: -1
replay-parser_1   | 	at skadistats.clarity.model.state.ClientFrame.getEntity(ClientFrame.java:24)
replay-parser_1   | 	at skadistats.clarity.processor.entities.Entities.processPacketEntities(Entities.java:435)
replay-parser_1   | 	at skadistats.clarity.processor.entities.Entities.processAndRunPacketEntities(Entities.java:337)
replay-parser_1   | 	at skadistats.clarity.processor.entities.Entities.onPacketEntities(Entities.java:332)
replay-parser_1   | 	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
replay-parser_1   | 	at skadistats.clarity.event.Event.raise(Event.java:41)
replay-parser_1   | 	at skadistats.clarity.processor.reader.InputSourceProcessor.processEmbedded(InputSourceProcessor.java:247)
replay-parser_1   | 	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
replay-parser_1   | 	at skadistats.clarity.event.Event.raise(Event.java:41)
replay-parser_1   | 	at skadistats.clarity.processor.reader.InputSourceProcessor.processSource(InputSourceProcessor.java:174)
replay-parser_1   | 	at skadistats.clarity.event.AbstractInvocationPoint.invoke(AbstractInvocationPoint.java:86)
replay-parser_1   | 	at skadistats.clarity.event.Event.raise(Event.java:41)
replay-parser_1   | 	at skadistats.clarity.processor.runner.AbstractFileRunner.initAndRunWith(AbstractFileRunner.java:39)
replay-parser_1   | 	at skadistats.clarity.processor.runner.SimpleRunner.runWith(SimpleRunner.java:33)
replay-parser_1   | 	at opendota.Parse.<init>(Parse.java:205)
replay-parser_1   | 	at opendota.Main$MyHandler.handle(Main.java:46)
replay-parser_1   | 	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
replay-parser_1   | 	at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
replay-parser_1   | 	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
replay-parser_1   | 	at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:700)
replay-parser_1   | 	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
replay-parser_1   | 	at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:672)
replay-parser_1   | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
replay-parser_1   | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
replay-parser_1   | 	at java.lang.Thread.run(Thread.java:748)
```

Also I tried matches https://www.opendota.com/matches/7840084622, https://www.opendota.com/matches/7838140144, the  result is still the same

For the test, I checked the parsing of the match that was a year ago - the parsing works (https://www.opendota.com/matches/7039984883)

**Comment by howardchung** [comment]
This might be related to the following issue: https://github.com/skadistats/clarity/issues/316

**Comment by howardchung** [comment]
Looks like the match is parsed now.
